Import('env')
from os import path

# --------------------------------------------------------------------------
name       = 'common_mcrt_logging'
sources    = env.DWAGlob('*.cc')
incdir     = [str(env.Dir('../..').srcnode())]
components = [
                'arras4_log'
             ]
# --------------------------------------------------------------------------
publicHeaders = [
   'McrtLogging.h'
]
env.DWAInstallInclude(publicHeaders, 'mcrt_computation/common/mcrt_logging')
env.DWAUseComponents(components)
env.Prepend (CPPPATH=incdir)
lib = env.DWASharedLibrary(name, sources)
target = env.DWAInstallLib(lib)
env.DWAComponent(name, LIBS=target, CPPPATH=incdir, COMPONENTS=components)
env.DWAInstallSConscriptStub(name, LIBS=target,
                             CPPPATH=[env.Dir('$INSTALL_DIR/include')],
                             COMPONENTS=components)
env.DWALinkValidate(name)
