Import('env')
from os import path

# --------------------------------------------------------------------------
name       = 'computation_engine_mcrt';
sources    = env.DWAGlob('*.cc')
incdir     = [str(env.Dir('../..').srcnode())]
components = [
    'common_grid_util',
    'common_rec_time',
    'engine_mcrt',
    'engine_merger',
    'share_util',
    'mcrt_messages',
    'message_api',
    'rendering_rndr',
    'rendering_shading',
    'render_logging',
    'render_cache',
    'render_util'
]

# --------------------------------------------------------------------------
publicHeaders = [
    'McrtUpdate.h',
    'MessageHistory.h',
    'RenderContextDriver.h',
    'RenderContextDriverMaster.h'
]
env.DWAInstallInclude(publicHeaders, 'mcrt_computation/engine/mcrt')
env.DWAUseComponents(components)
env.Prepend (CPPPATH=incdir)
lib = env.DWASharedLibrary(name, sources)
target = env.DWAInstallLib(lib)
env.DWAComponent(name, LIBS=target, CPPPATH=incdir, COMPONENTS=components)
env.DWAInstallSConscriptStub(name, LIBS=target,
                             CPPPATH=[env.Dir('$INSTALL_DIR/include')],
                             COMPONENTS=components)
env.DWALinkValidate(name)
